backend:
  name: git-gateway
  repo: zanonnicola/meletto
  branch: live

media_folder: static/assets
public_folder: /assets

collections:
  - label: 'Works'
    name: 'works'
    folder: 'src/pages/works'
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Main Image", name: "thumbnail", widget: "image"}
      - {label: "Hover Image", name: "thumbnailOnHover", widget: "image"}
