backend:
  name: git-gateway
  repo: zanonnicola/meletto
  branch: live

media_folder: static/img
public_folder: /assets

collections:
  - label: 'Works Gallery'
    name: 'gallery'
    folder: 'src/pages/gallery'
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Order", name: "order", widget: "number", valueType: "int", min: 1, default: 1}
      - {label: "Main Image", name: "thumbnail", widget: "image"}
      - {label: "Hover Image", name: "thumbnailOnHover", widget: "image"}
  
  - label: 'Work Single'
    name: 'work'
    folder: 'src/pages/works'
    create: true
    fields:
      - {label: 'Page', name: 'isPage', widget: 'hidden', default: true }
      - {label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'work' }
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Sub Title", name: "subtitle", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Link", name: "link", widget: "string", default: ''}
      - label: "Pictures"
        name: 'pictures'
        widget: 'list'
        fields: 
          - { label: Image, name: image, widget: image }
